---
title: "EDS212_Day3_Part2"
output: html_document
date: "2022-08-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

```{r}
food <- c("banana", "apple", "carrot")
meal <- c("breakfast", "snack", "lunch")
food_mass_g <- c(14.8, 19.2, 11.5)

squirrel_meals <- data.frame(food, meal, food_mass_g)
squirrel_meals
```

## Creating & working with vectors

### Make some vectors

```{r}
marmots <- c("blue", "green", 4, "yellow")

# Check class
class(marmots)
```

```{r}
pika <- c(12.4, 6.8, 5.3, 4.2, 8.8, 8.5)

#Check class
class(pika)

# Scalar multiplier
scalar_pika <- 5.2 * pika
scalar_pika
```

```{r}
bananas <- c(1, 2, 3)
apples <- c(6, 7, 8)
class(bananas)
class(apples)

bananas + apples
bananas - apples

# dot product
bananas %*% apples
```

```{r}

my_values <- seq(from = 1, to = 10)

# If you dont include by or length, it will assume that you want the sequence to increase in increments of 1
```

```{r}
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)
my_matrix

5 * my_matrix
class(my_matrix)
```

```{r}
glimpse(penguins)
```

```{r}

```

